Model delivery service
ValeriiaMishchenko/course pull request #2
Opened 2021-04-17 20:29 UTC by ValeriiaMishchenko

Model delivery service was created

2021-04-17 20:37 UTC, serhii-shkodenko requested changes

2021-04-17 20:37 UTC, serhii-shkodenko commented on DeliveryService/DeliveryService/Business.cs
> +    class Business
Добавь пожалуйста, модифкатор доступа. Просмотри все модели.

2021-04-17 20:37 UTC, serhii-shkodenko commented on DeliveryService/DeliveryService/Business.cs
> +        public decimal DeliveryCost { get; set; }
Лучше использовать `Fee` вместо `Cost`. Просмотри, пожалуйста, все модели.

2021-04-17 20:37 UTC, serhii-shkodenko commented on DeliveryService/DeliveryService/Business.cs
> +        Business()
Не хватает модификатора доступа. Просмотри, пожалуйста, все модели.

2021-04-17 20:37 UTC, serhii-shkodenko commented on DeliveryService/DeliveryService/Discount.cs
> +        Dictionary<string, decimal> PromoCodes;
Лучше использовать наболее базовые типы для контрактов. Поэтому предложу `IDictionary<T>` или даже `IKeyValuePair<K,V>`.

2021-04-17 20:37 UTC, serhii-shkodenko commented on DeliveryService/DeliveryService/Order.cs
> +        decimal GetFinalPrice(decimal fullPrice)
Не хватает модификатор доступа.

2021-04-18 12:05 UTC, serhii-shkodenko requested changes
Поправь эти замечания и можно будет мержить.

2021-04-18 12:05 UTC, serhii-shkodenko commented on DeliveryService/DeliveryService/Dish.cs
> +        public decimal Weight { get; set; }
Для веса не нужна такая высокая точность, как для цен. Можно выбрать другой тип с плавающей точкой.

2021-04-18 12:05 UTC, serhii-shkodenko commented on DeliveryService/DeliveryService.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "DeliveryService", "DeliveryService\DeliveryService.csproj", "{12BFBBD4-E651-4D5E-A600-817BF12A0E01}"
Зачем ты удаляешь проект с первым заданием? Его не нужно удалять. Создай в решении новый проект и продолжай работу уже в нем.

2021-04-18 15:04 UTC, ValeriiaMishchenko commented on DeliveryService/DeliveryService.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "DeliveryService", "DeliveryService\DeliveryService.csproj", "{12BFBBD4-E651-4D5E-A600-817BF12A0E01}"
Думала, что нужно для каждого задания создавать новый проект, но перечитав git-flow поняла что ошиблась, там написано только про создание новых веток для каждого задания.

2021-04-20 19:42 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-04-22 13:04 UTC, merged